version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file:
      - mongo.env
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile.dev
    env_file: ./backend/.env
    ports:
      - '4000:4000'
    volumes:
      - public:/app/public
      - uploads:/app/uploads
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build:
      context: './frontend'
      dockerfile: Dockerfile.dev
    env_file: ./frontend/.env
    ports:
      - '5173:5173'
    stdin_open: true # -i 옵션과 동일
    tty: true # -t 옵션과 동일
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  data:
  public:
  uploads:
