# 빌드 단계
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# 'swagger.yaml' 파일을 빌드 단계에 복사
COPY src/utils/swagger.yaml src/utils/

RUN npm run build

# 실행 단계
FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules/
# 'swagger.yaml' 파일을 빌드 단계에서 실행 단계로 복사
COPY --from=builder /app/src/utils/swagger.yaml ./src/utils/swagger.yaml

COPY package.json .

CMD ["node", "dist/server.js"]
